#!/bin/bash



SINK=`pactl list sinks | grep -B 1 "State: RUNNING" | grep "Sink" | awk '{print $2}'`

[[ $SINK == "" ]] && SINK=0

volume=`pulsemixer --get-volume | awk '{print $1}'`
mute=`pulsemixer --get-mute`

if [[ $mute = 1 ]]
then
  echo 'Muted'
else
  echo "$volume%" 
fi
