#!/bin/bash

time_to_alert=60
commands_to_always_alert=('blaze' 'demo1' 'demo2' 'demo3' 'run1' 'run2' 'run3' 'test-long')
LAST_HISTORY_NUMBER=""
prompt_command() {
  local history_output=$(HISTTIMEFORMAT="%s " history 1)
  local history_number=$(echo $history_output | awk '{print $1}')
  local trim_hist=$(echo $history_output | xargs)
  local rest=${trim_hist#* }
  local started_at=$(echo $rest | awk '{print $1}')
  local last_command=${rest#* }
  local finished_at=$(date +%s)

  local elapsed_seconds=$(( $finished_at - $started_at ))
  local ds=$((elapsed_seconds % 60))
  local dm=$(((elapsed_seconds / 60) % 60))
  local dh=$((elapsed_seconds / 3600))
  local elapsed=$(printf '%02d:%02d:%02d' $dh $dm $ds)

  if [[ ! -z "$LAST_HISTORY_NUMBER" &&
	"$history_number" != "$LAST_HISTORY_NUMBER" ]] &&
    (( $finished_at - $started_at > $time_to_alert )); then
    if [ -n "$DISPLAY" ]; then
      notify-send "Long running command finished in ${elapsed}" "$last_command"
    else
      echo "Finished in ${elapsed}"
    fi
  else
    if [[ $last_command == *"blaze"* ]]
    then
      if [ -n "$DISPLAY" ]; then
        notify-send "Blaze command finished in ${elapsed}" '<a href="http://sponge/lucky">Open Sponge</a>'
      else
        echo "Finished in ${elapsed}"
      fi
    else
      for command in "${commands_to_always_alert[@]}"
      do
        if [[ $last_command == *"$command"* ]]
        then
          if [ -n "$DISPLAY" ]; then
            notify-send "Long running command finished in ${elapsed}" "$last_command"
          else
            echo "Finished in ${elapsed}"
          fi
        fi
      done
    fi
  fi

  LAST_HISTORY_NUMBER=$history_number
}

PROMPT_COMMAND=prompt_command

