#!/bin/bash

alias xcl='xclip -selection clipboard'
alias tm='~/scripts/tmux-open-session.sh'
alias top='top -o "%MEM"'
alias rebash='source ~/.bashrc'
alias gitc='git-cola'
alias ag='ag --path-to-agignore=~/.agignore'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

#fzf aliases
alias vimf='vim $(fzf)'
alias catf='cat $(fzf)'
alias cdf='cd $(fzf)'

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'
    alias lstest='ls'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi
alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias lh='ls *.h'
alias lt='ls *test.cc'
alias lc='ls *.cc'

# git aliases
alias gik="gitk --argscmd='git for-each-ref --format=\"%(refname)\" refs/heads refs/tags refs/exported' &"
alias grd="git rev-parse --show-toplevel"
alias bb='echo $(git rev-parse --show-toplevel)/google3/blaze-bin$(git rev-parse --show-prefix | sed s/google3//)'
alias lsbb='ls $(bb)'
alias cdbb='cd $(bb)'
