#!/bin/bash

pipe=/tmp/xmobar_google
[[ -e $pipe ]] || mkfifo $pipe
chmod 766 $pipe
echo "" > $pipe

google=$HOME/.xmonad/scripts/google

prev_status=''

while true; do
  echo "start loop"
  output=();
  output+=($($google certificates))
  output+=($($google corp_notifier))
  output+=($($google goobuntu_backups))
  output+=($($google goobuntu_check))
  output+=($($google goobuntu_updater))
  output+=($($google prodcertstatus))
  joined=""
  for line in ${output[@]} ; do
    [[ $line != "" ]] && joined="$joined, $line"
  done
  joined=${joined:2}

  [[ $joined != $prev_status ]] && echo $joined > $pipe || echo $(date +"%H:%M") > $pipe
  echo $joined
  sleep 5
done

