#!/bin/bash

MASTER_SCREEN=$1
[[ $MASTER_SCREEN = "" ]] && MASTER_SCREEN="primary"

echo "starting on $MASTER_SCREEN" >> ~/trayerstart.txt
[[ $(pidof trayer) ]] && kill -9 $(pidof trayer)
echo "done"

trayer \
--edge top \
--align right \
--SetDockType true \
--SetPartialStrut true \
--expand true \
--height 23 \
--widthtype pixel \
--width 256 \
--transparent true \
--alpha 0 \
--monitor $MASTER_SCREEN \
--tint 0x000000 &
