#!/bin/bash

echo 'trayer' >> $HOME/start.txt

[[ $(pidof trayer) ]] || \
  trayer \
    --edge top \
    --align right \
    --SetDockType true \
    --SetPartialStrut true \
    --expand true \
    --height 20 \
    --widthtype pixel \
    --width 192 \
    --transparent true \
    --monitor 1 \
    --tint 0x000000 &
