#!/bin/bash

PRIMARY_SCREEN=$1
[[ $PRIMARY_SCREEN = "" ]] && PRIMARY_SCREEN="primary"

echo "starting on $PRIMARY_SCREEN" >> ~/trayerstart.txt
[[ $(pidof trayer) ]] && kill -9 $(pidof trayer)
echo "done"

trayer \
--edge top \
--align right \
--SetDockType true \
--SetPartialStrut true \
--expand true \
--height 30 \
--widthtype pixel \
--width 200 \
--transparent true \
--alpha 0 \
--monitor $PRIMARY_SCREEN \
--tint 0x000000 &
